name: CI setup for Go #Name the workflow
on: #on event keyword
  push:
    branches: [main] #identify branch
    
jobs: #job to execute on event
  my-job:
    name: My Job
    runs-on: ubuntu-16.04 #specify OS for virtual machine
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello There! #run terminal command
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5 # optional
    - name: Show Go version # verify that Go is installed
      run: |
        go version # show Go version
        
    - name: Checkout our code #pull repo code to virtual env
      uses: actions/checkout@v2
      
    - name: Check file system #check virtual env has pulled file
      run: |
        ls
        cat calc.go #print content of calc.go
